# Generated by Django 5.1.4 on 2025-03-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravg',
            name='id',
        ),
        migrations.AlterField(
            model_name='useravg',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
